//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMDRMC.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildScreen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChildScreen()
        {
            this.RoleDetails = new HashSet<RoleDetail>();
        }
    
        public long ScreenID { get; set; }
        public string Name { get; set; }
        public long MainScreenID { get; set; }
        public Nullable<bool> Activate { get; set; }
    
        public virtual MainScreen MainScreen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleDetail> RoleDetails { get; set; }
    }
}
