//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMDRMC.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDetail
    {
        public long RoleID { get; set; }
        public long ScreenID { get; set; }
        public int AccessID { get; set; }
        public Nullable<bool> Activate { get; set; }
    
        public virtual AccessDetail AccessDetail { get; set; }
        public virtual ChildScreen ChildScreen { get; set; }
        public virtual Role Role { get; set; }
    }
}
