//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMDRMC.Data.Sql
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleDetail
    {
        public long RoleID { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<long> Child { get; set; }
        public Nullable<long> Accesser { get; set; }
        public Nullable<long> Viewer { get; set; }
    }
}
